"""GLiREL-based zero-shot relation extraction for Step 3.

This module scores relations between all named-entity pairs in one paragraph
using GLiREL in a single forward pass.
"""

from __future__ import annotations

from collections import defaultdict
from itertools import combinations


RELATION_LABELS: dict[str, str] = {
    "technology_transfer": (
        "technology transfer: technology transfer via markets or non-market interactions is the "
        "core activity in an innovation system (Ranga & Etzkowitz 2013); universities generate and "
        "transfer technology, especially in biotechnology, nanotechnology, ICT, or medical "
        "technologies; includes technology transfer offices, science parks, business incubators, "
        "start-up accelerators, and venture capital capacities created as intermediary elements to "
        "facilitate the capitalization of knowledge; also includes university involvement in "
        "intellectual property protection, patenting, licensing, and spin-off formation; the "
        "exchange of knowledge, research results, patents, or technical expertise between "
        "university, industry, and government through market or non-market mechanisms"
    ),
    "collaboration_conflict_moderation": (
        "collaboration and conflict moderation: a specific form of interaction in triadic entities "
        "which have a higher potential for turning tension and conflict of interest into convergence "
        "and confluence of interest, compared to dyadic relationships which are more subject to "
        "collapse into oppositional modes (Ranga & Etzkowitz 2013); includes task conflict — "
        "functional, cognitive or constructive conflict that is content-driven and generated by "
        "differences of opinions between functional departments — and relationship conflict — "
        "dysfunctional or affective conflict generated by incompatibilities between different "
        "personalities or institutions; conflict resolution through institutional dialogue, "
        "public-private partnerships, joint research programs, co-funded initiatives, and "
        "government policies that establish legal frameworks for university-industry collaboration"
    ),
    "collaborative_leadership": (
        "collaborative leadership: an integral part of collaboration and conflict moderation "
        "capacity; innovation organizers as individual or institutional leaders play a key role — "
        "they connect people from different sectors to bridge gaps, bring together differing views, "
        "generate consensus, and balance conflicts of interest (Ranga & Etzkowitz 2013); the "
        "innovation organizer occupies a key institutional position, enunciates a vision for "
        "knowledge-based development, and exercises convening power to bring leadership of "
        "institutional spheres together; coordinates a mix of top-down and bottom-up processes and "
        "innovation stakeholders from different organizational backgrounds; cross-institutional "
        "entrepreneurship spanning the Triple Helix spheres; includes national strategy "
        "coordinators, science-policy intermediaries, and agency leaders who align policy with "
        "innovation activity across university, industry, and government"
    ),
    "substitution": (
        "substitution: this type of interaction arises when institutional spheres fill gaps that "
        "emerge when another sphere is weak (Ranga & Etzkowitz 2013); government agencies taking "
        "up, in addition to their traditional function of regulation and control, that of investment "
        "and provision of public venture capital — a traditional task for the industry sphere; "
        "universities engaging in technology transfer and firm formation, providing support and "
        "funding to encourage entrepreneurial ventures, thus enacting some of the traditional role "
        "of industry; industry taking the role of the university in developing proprietary education "
        "and training solutions; in countries with no or weak regional governments, universities, "
        "firms, or regional development agencies may come forward to play an innovation organizer "
        "role; one sphere takes on functions normally performed by another because the other is "
        "absent, weak, or underfunded"
    ),
    "networking": (
        "networking in formal and informal structures at national, regional, and international "
        "level is a manifestation of the collective nature of science, technology and innovation "
        "(Ranga & Etzkowitz 2013); networks have been described as techno-economic networks and "
        "networks of innovators — an organizational form better suited than hierarchies or markets, "
        "more flexible than hierarchies, more invested in the public good than markets; research "
        "networks in academia compared to a joint venture generating a division of labour among "
        "participants; reflects the growing non-linearity and interactivity of innovation processes; "
        "includes membership in standards bodies, industry associations, research consortia, "
        "European Technology Platforms, Joint Technology Initiatives, bilateral agreements, "
        "intergovernmental forums, cross-sector advisory boards, and university-industry-government "
        "cooperation networks at any geographic scale"
    ),
}
RELATION_TYPES = list(RELATION_LABELS.keys())


def _build_token_spans(para_text: str) -> list[tuple[int, int]]:
    """Build char spans (start, end-exclusive) for whitespace tokens."""
    spans: list[tuple[int, int]] = []
    in_token = False
    token_start = 0

    for idx, char in enumerate(para_text):
        if char.isspace():
            if in_token:
                spans.append((token_start, idx))
                in_token = False
            continue

        if not in_token:
            token_start = idx
            in_token = True

    if in_token:
        spans.append((token_start, len(para_text)))

    return spans


def _char_to_word_span(
    para_text: str,
    char_start: int,
    char_end: int,
    token_spans: list[tuple[int, int]] | None = None,
) -> tuple[int, int]:
    """Map paragraph-relative char offsets to word-token span (start, end-exclusive)."""
    spans = token_spans if token_spans is not None else _build_token_spans(para_text)
    if not spans:
        return (0, 1)

    text_len = len(para_text)
    start = max(0, min(int(char_start), text_len))
    end = max(start + 1, min(int(char_end), text_len))

    word_start = None
    for idx, (_, tok_end) in enumerate(spans):
        if tok_end > start:
            word_start = idx
            break

    if word_start is None:
        return (0, 1)

    word_end_inclusive = None
    for idx, (tok_start, _) in enumerate(spans):
        if tok_start < end:
            word_end_inclusive = idx
        else:
            break

    if word_end_inclusive is None:
        return (word_start, min(word_start + 1, len(spans)))

    word_end = word_end_inclusive + 1
    if word_end <= word_start:
        word_end = min(word_start + 1, len(spans))
    return (word_start, word_end)


class GLiRELRelationScorer:
    """Zero-shot relation scorer using GLiREL."""

    def __init__(
        self,
        model_name: str = "jackboyla/glirel-large-v0",
        threshold: float = 0.5,
        device: str = "auto",
    ) -> None:
        self.model_name = model_name
        self.threshold = threshold
        self._device = self._resolve_device(device)
        self._model = None
        self._label_to_key = {
            value.lower(): key for key, value in RELATION_LABELS.items()
        }
        self._load_model()

    def score_paragraph(
        self,
        para_text: str,
        para_start_char: int,
        entities: list[dict],
    ) -> list[dict]:
        """Score all entity pairs in one paragraph.

        Returns one result per pair in ``combinations(range(len(entities)), 2)``
        order, each containing relation type, confidence, all scores, and direction.
        """
        pair_indices = list(combinations(range(len(entities)), 2))
        if not pair_indices:
            return []

        tokenized_text = para_text.split()
        token_spans = _build_token_spans(para_text)
        if not tokenized_text:
            tokenized_text = ["[EMPTY]"]
            token_spans = [(0, max(1, len(para_text)))]

        word_spans: list[tuple[int, int]] = []
        ner: list[list[int | str | float]] = []
        token_count = len(tokenized_text)

        for entity in entities:
            mention_start = self._to_int(entity.get("mention_start_char", -1), -1)
            mention_end = self._to_int(entity.get("mention_end_char", -1), -1)

            if mention_start < 0 or mention_end <= mention_start:
                span = (0, 1)
            else:
                rel_start = mention_start - para_start_char
                rel_end = mention_end - para_start_char
                span = _char_to_word_span(
                    para_text, rel_start, rel_end, token_spans=token_spans
                )

            start = max(0, min(span[0], token_count - 1))
            end = max(start + 1, min(span[1], token_count))
            span = (start, end)

            word_spans.append(span)
            ner.append([start, end, "ENTITY", 1.0])

        label_strings = [RELATION_LABELS[key] for key in RELATION_TYPES]
        try:
            # GLiREL>=1.x API: token list via `text` and NER via separate arg.
            predictions = self._model.predict_relations(
                tokenized_text,
                label_strings,
                threshold=0.0,
                ner=ner,
                top_k=len(RELATION_TYPES),
            )
        except TypeError:
            # Backward-compatible fallback for legacy API variants.
            data = [{"tokenized_text": tokenized_text, "ner": ner}]
            predictions = self._model.predict_relations(
                data,
                label_strings,
                threshold=0.0,
                top_k=len(RELATION_TYPES),
            )
        except Exception as exc:
            print(f"[GLiREL][WARN] Relation prediction failed for paragraph: {exc}")
            return self._empty_results(pair_indices)

        paragraph_predictions: list[dict] = []
        if isinstance(predictions, list) and predictions:
            if isinstance(predictions[0], dict):
                paragraph_predictions = predictions
            elif isinstance(predictions[0], list):
                paragraph_predictions = predictions[0]
        if not paragraph_predictions:
            return self._empty_results(pair_indices)

        span_to_indices: dict[tuple[int, int], list[int]] = defaultdict(list)
        for idx, span in enumerate(word_spans):
            span_to_indices[span].append(idx)

        pair_scores: dict[tuple[int, int], dict[str, float]] = defaultdict(dict)

        for prediction in paragraph_predictions:
            if not isinstance(prediction, dict):
                continue

            head_span = self._span_tuple(prediction.get("head_pos"))
            tail_span = self._span_tuple(prediction.get("tail_pos"))
            if head_span is None or tail_span is None:
                continue

            head_idx = self._span_to_entity_index(
                head_span, span_to_indices, word_spans
            )
            tail_idx = self._span_to_entity_index(
                tail_span, span_to_indices, word_spans
            )
            if head_idx is None or tail_idx is None or head_idx == tail_idx:
                continue

            relation_key = self._label_to_relation_key(prediction.get("label"))
            if relation_key is None:
                continue

            score = self._to_float(prediction.get("score", 0.0), 0.0)
            if score > pair_scores[(head_idx, tail_idx)].get(relation_key, 0.0):
                pair_scores[(head_idx, tail_idx)][relation_key] = score

        results: list[dict] = []
        for i, j in pair_indices:
            all_scores: dict[str, float] = {}
            best_relation = RELATION_TYPES[0]
            best_confidence = -1.0
            best_direction = "A->B"

            for relation_key in RELATION_TYPES:
                forward = pair_scores.get((i, j), {}).get(relation_key, 0.0)
                reverse = pair_scores.get((j, i), {}).get(relation_key, 0.0)
                if forward >= reverse:
                    best = forward
                    direction = "A->B"
                else:
                    best = reverse
                    direction = "B->A"

                all_scores[relation_key] = round(best, 6)

                if best > best_confidence:
                    best_confidence = best
                    best_relation = relation_key
                    best_direction = direction

            confidence = round(best_confidence, 6)
            if best_confidence < self.threshold:
                results.append(
                    {
                        "relation_type": "no_explicit_relation",
                        "confidence": confidence,
                        "all_scores": all_scores,
                        "direction": best_direction,
                    }
                )
                continue

            results.append(
                {
                    "relation_type": best_relation,
                    "confidence": confidence,
                    "all_scores": all_scores,
                    "direction": best_direction,
                }
            )

        return results

    def _empty_results(self, pair_indices: list[tuple[int, int]]) -> list[dict]:
        zero_scores = {relation: 0.0 for relation in RELATION_TYPES}
        return [
            {
                "relation_type": "no_explicit_relation",
                "confidence": 0.0,
                "all_scores": dict(zero_scores),
                "direction": "A->B",
            }
            for _ in pair_indices
        ]

    def _load_model(self) -> None:
        import sys

        if sys.version_info < (3, 10):
            raise ImportError(
                "GLiREL requires Python >= 3.10, but the active interpreter is "
                f"{sys.version.split()[0]}. Recreate the venv with Python 3.10+ "
                "(recommended: 3.11)."
            )

        try:
            from glirel import GLiREL
        except ImportError as exc:
            msg = str(exc).lower()
            if "loguru" in msg:
                raise ImportError(
                    "Missing dependency 'loguru' required by glirel. "
                    "Install with: python -m pip install loguru"
                ) from exc
            raise ImportError(
                "glirel is required for Step 3 relation extraction. "
                "Install with: pip install glirel"
            ) from exc

        print(f"[GLiREL] Loading model '{self.model_name}' on device '{self._device}' ...")

        self._model = None
        last_type_error: TypeError | None = None
        load_attempts = [
            {"map_location": self._device, "proxies": None, "resume_download": False},
            {"device": self._device, "proxies": None, "resume_download": False},
            {"proxies": None, "resume_download": False},
            {"map_location": self._device},
            {"device": self._device},
            {},
        ]

        for kwargs in load_attempts:
            try:
                self._model = GLiREL.from_pretrained(self.model_name, **kwargs)
                break
            except TypeError as exc:
                last_type_error = exc

        if self._model is None and hasattr(GLiREL, "_from_pretrained"):
            for map_location in [self._device, "cpu"]:
                try:
                    self._model = GLiREL._from_pretrained(
                        model_id=self.model_name,
                        revision=None,
                        cache_dir=None,
                        force_download=False,
                        proxies=None,
                        resume_download=False,
                        local_files_only=False,
                        token=None,
                        map_location=map_location,
                        strict=False,
                    )
                    break
                except TypeError as exc:
                    last_type_error = exc

        if self._model is None and last_type_error is not None:
            raise last_type_error

        if self._model is None:
            raise RuntimeError("Failed to load GLiREL model for an unknown reason.")

        if hasattr(self._model, "to"):
            try:
                self._model.to(self._device)
            except Exception:
                pass

        print("[GLiREL] Model loaded")

    def _label_to_relation_key(self, label: object) -> str | None:
        raw = str(label).strip().lower()
        if not raw:
            return None
        if raw in RELATION_LABELS:
            return raw
        return self._label_to_key.get(raw)

    @staticmethod
    def _span_tuple(raw: object) -> tuple[int, int] | None:
        if not isinstance(raw, (list, tuple)) or len(raw) != 2:
            return None
        try:
            start = int(raw[0])
            end = int(raw[1])
        except (TypeError, ValueError):
            return None
        if end <= start:
            return None
        return (start, end)

    @classmethod
    def _span_to_entity_index(
        cls,
        span: tuple[int, int],
        span_to_indices: dict[tuple[int, int], list[int]],
        entity_spans: list[tuple[int, int]],
    ) -> int | None:
        exact = span_to_indices.get(span)
        if exact:
            return exact[0]

        best_idx = None
        best_overlap = 0
        for idx, entity_span in enumerate(entity_spans):
            overlap = cls._span_overlap(span, entity_span)
            if overlap > best_overlap:
                best_overlap = overlap
                best_idx = idx
        return best_idx if best_overlap > 0 else None

    @staticmethod
    def _span_overlap(a: tuple[int, int], b: tuple[int, int]) -> int:
        return max(0, min(a[1], b[1]) - max(a[0], b[0]))

    @staticmethod
    def _to_int(value: object, default: int) -> int:
        try:
            return int(value)
        except (TypeError, ValueError):
            return default

    @staticmethod
    def _to_float(value: object, default: float) -> float:
        try:
            return float(value)
        except (TypeError, ValueError):
            return default

    @staticmethod
    def _resolve_device(device: str) -> str:
        if device != "auto":
            return device
        try:
            import torch

            if torch.cuda.is_available():
                return "cuda"
            if torch.backends.mps.is_available():
                return "mps"
        except Exception:
            pass
        return "cpu"
